version: '3.7'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-payment-service:
    build:
      context: .
      target: development
    command: sh -c "npm run test"
