version: '3.7'
services:
  bpdts-test-app-node:
    build: 
      context: .
      target: production
    image: bpdtstestapp
    environment:
      PORT: 8000
    volumes:
      - ./server/:/home/node/server/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json
    ports:
      - "8000:8000"
